#!/usr/bin/env python3

import sys
import GeoIP
import re

IPEXP = re.compile(r'\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b')
GREEN = '\x1b[42m'
RESET = '\x1b[0m'
COLORS = True

def replace_ips(text, geoip):

    def ip_match(m):
        ip = m.group(0)
        # a, b, c, d = m.groups()
        info = geoip.record_by_addr(ip)
        if info is None:
            return "{}{} {{?}}{}".format(GREEN, ip, RESET)
        else:
            city = info['city']
            if city is None:
                city = "?"
            return "{}{} {{{}, {}}}{}".format(
                GREEN, ip, city, info['country_code'],
                RESET)
    x = IPEXP.sub(ip_match, text)
    return x

if __name__ == '__main__':
    gi = GeoIP.open("/usr/share/GeoIP/GeoIPCity.dat", GeoIP.GEOIP_STANDARD)
    for line in sys.stdin:
        line = replace_ips(line, gi)
        sys.stdout.write(line)
